name = "gameoflife_gleam"
version = "1.0.0"

description = "Conway's Game of Life implemented in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "afarinetti", repo = "https://github.com/afarinetti/gameoflife-gleam" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
